Description: testVPC

Resources:
  devopsVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: "true"
      Tags:
        - Key: stack
          Value: production
